### ISSUE TITLE
BUG: Assumes a storage path is set

### ISSUE THREAD

**Issue by jdevera** [marcelbrueckner/paperless-ngx-cli#3]
I don't have a storage path set. Things still work. But this tool has a strong assumption on their existence and it fails to fetch a document if there isn't one.

```
❯ pngx document show 22
Traceback (most recent call last):
  File "/Users/jdevera/.local/bin/pngx", line 8, in <module>
    sys.exit(launch())
             ^^^^^^^^
  File "/Users/jdevera/.local/pipx/venvs/pypaperless-cli/lib/python3.12/site-packages/pypaperless_cli/app.py", line 186, in launch
    app.meta()
  File "/Users/jdevera/.local/pipx/venvs/pypaperless-cli/lib/python3.12/site-packages/cyclopts/core.py", line 892, in __call__
    return command(*bound.args, **bound.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdevera/.local/pipx/venvs/pypaperless-cli/lib/python3.12/site-packages/pypaperless_cli/app.py", line 177, in main
    app(tokens)
  File "/Users/jdevera/.local/pipx/venvs/pypaperless-cli/lib/python3.12/site-packages/cyclopts/core.py", line 890, in __call__
    return asyncio.run(command(*bound.args, **bound.kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jdevera/.local/pipx/venvs/pypaperless-cli/lib/python3.12/site-packages/pypaperless_cli/commands/document.py", line 50, in show
    storage_path = await paperless.storage_paths(document.storage_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdevera/.local/pipx/venvs/pypaperless-cli/lib/python3.12/site-packages/pypaperless/models/mixins/helpers/callable.py", line 38, in __call__
    await item.load()
  File "/Users/jdevera/.local/pipx/venvs/pypaperless-cli/lib/python3.12/site-packages/pypaperless/models/base.py", line 129, in load
    data = await self._api.request_json("get", self._api_path, params=self._params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdevera/.local/pipx/venvs/pypaperless-cli/lib/python3.12/site-packages/pypaperless/api.py", line 316, in request_json
    res.raise_for_status()
  File "/Users/jdevera/.local/pipx/venvs/pypaperless-cli/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1093, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url='https://paperless:443/api/storage_paths/None/'

```

**Comment by marcelbrueckner** [comment]
Thanks for your bug report. Yeah, I didn't think about the fact that the storage path can be left empty. Will add a fix in the next days.
